"""Platform-independent domain foundation for G01 and later standards."""

from .decimal_policy import DecimalPolicy, DecimalPolicyError
from .errors import (
    DomainError,
    DomainValidationError,
    IssueLevel,
    ValidationProblem,
    contains_errors,
    contains_warnings,
)
from .models import (
    AccountingInput,
    AccountingPeriod,
    AccountingRecord,
    ActivityData,
    ActivityDataSource,
    CalculationLine,
    CalculationResult,
    EmissionSourceSelection,
    Factor,
    OfficialStatus,
    Parameter,
    ParameterSelectionMethod,
    ParameterSnapshot,
    ParameterType,
    PeriodType,
    RecordStatus,
    ReviewStatus,
    SettingEntry,
    Settings,
    SourceDocument,
    SourceType,
    Standard,
    ValueType,
)
from .repositories import ParameterRepository, RecordRepository, SettingsRepository, StandardRepository
from .units import IncompatibleUnitError, UnitDefinition, UnitError, UnitService, UnknownUnitError

__all__ = [
    "AccountingInput",
    "AccountingPeriod",
    "AccountingRecord",
    "ActivityData",
    "ActivityDataSource",
    "CalculationLine",
    "CalculationResult",
    "DecimalPolicy",
    "DecimalPolicyError",
    "DomainError",
    "DomainValidationError",
    "EmissionSourceSelection",
    "Factor",
    "IncompatibleUnitError",
    "IssueLevel",
    "OfficialStatus",
    "Parameter",
    "ParameterRepository",
    "ParameterSelectionMethod",
    "ParameterSnapshot",
    "ParameterType",
    "PeriodType",
    "RecordRepository",
    "RecordStatus",
    "ReviewStatus",
    "SettingEntry",
    "Settings",
    "SettingsRepository",
    "SourceDocument",
    "SourceType",
    "Standard",
    "StandardRepository",
    "UnitDefinition",
    "UnitError",
    "UnitService",
    "UnknownUnitError",
    "ValidationProblem",
    "ValueType",
    "contains_errors",
    "contains_warnings",
]
